# Figaro configuration file
# For further instructions see: http://sites.psu.edu/dltdocs/?p=4073

development:
  service_name: "localhost"
  service_instance: "localhost"
  virtual_host: "http://localhost:3000/"
  network_ingest_directory: 'tmp/ingest-development'
  extraction_directory: 'tmp/extract-development'
  storage_directory: 'public/files'
test:
  service_name: "example-test"
  service_instance: "example-test"
  virtual_host: "http://test.com/"
  network_ingest_directory: 'tmp/ingest-test'
  extraction_directory: 'tmp/extract-test'
  storage_directory: 'public/files'

production:
