development:
  adapter: solr
  url: http://<%= ENV['SOLR_HOST'] || "127.0.0.1" %>:<%= ENV['SOLR_DEVELOPMENT_PORT'] || "8983" %>/solr/<%= ENV['SOLR_CORE'] || 'cho-development2' %>
test: &test
  adapter: solr
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/cho-test
production:
  adapter: solr
  url: http://production.server/solr/cho-production
