# Default values for fo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: harbor.dsrd.libraries.psu.edu/library/cho
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecrets: dsrd-dockerhub

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # limits:
  #   memory: 1024Mi
  requests:
    memory: 256Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

rails:
  environment: production

# PVC for explore and workflow data
persistence:
  enabled: true
  storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

webaccess:
  enabled: false
  image: harbor.dsrd.libraries.psu.edu/public/apache-docker-webaccess:v3.0.2

certmanager:
  enabled: false
  issuer:
    name: letsencrypt-prod-route53
    kind: ClusterIssuer
  # secretName: ""
  # commonName: ""
  dnsNames: []
  challenge:
    type: dns01
    provider: route53

redis:
  enabled: true
  master:
    persistence:
      enabled: false
  cluster:
    enabled: false

solr:
  image:
    # tag: 7.1.0
  persistence:
    enabled: true
    size: 8Gi
    accessModes:
    - ReadWriteOnce
  enabled: true
  core: cho

postgresql:
  db:
    username: cho
    name: cho
    # password:
  persistence:
    enabled: true
    storageClass: hostpath
  enabled: true

global:
  vault:
    enabled: false
    mountPath: auth/k8s-dsrd-dev
    address: https://vault.dsrd.libraries.psu.edu:8200
    path: secret/data/app/cho/dev
    role: cho-dev
